name: logger_flutter_plus
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.5

homepage: https://github.com/Oliinyk-Volodymyr/logger_flutter_plus

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  collection: ^1.16.0
  path_provider: ^2.0.14
  sensors_plus: ^2.0.1
  share_plus: ^6.3.4
