name: logger_flutter_plus
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.5

homepage: https://github.com/Oliinyk-Volodymyr/logger_flutter_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.1
  collection: ^1.17.1
  path_provider: ^2.0.15
  sensors_plus: ^3.0.2
  share_plus: ^7.0.2
  async: ^2.11.0
